# Generated by Django 5.1.4 on 2025-01-06 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cateagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=500)),
                ('ActualPrice', models.IntegerField()),
                ('OfferPrice', models.IntegerField()),
                ('catFor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.cateagory')),
            ],
        ),
    ]
