# Generated by Django 5.1.4 on 2025-01-08 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Firstname', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('Memberimage', models.CharField(max_length=100, null=True)),
                ('Gender', models.CharField(max_length=7)),
                ('Email', models.CharField(max_length=50)),
                ('Contactno', models.CharField(max_length=50)),
                ('Visitcount', models.IntegerField()),
                ('DOB', models.DateField()),
                ('DOJ', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Productimage',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='MemberOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Odate', models.DateField()),
                ('MemberFor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.member')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=500)),
                ('OfferPrice', models.IntegerField()),
                ('Qty', models.IntegerField()),
                ('PriceQty', models.IntegerField()),
                ('MemberOrderFor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.memberorder')),
                ('ProductFor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.product')),
            ],
        ),
        migrations.CreateModel(
            name='TempCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=500)),
                ('OfferPrice', models.IntegerField()),
                ('Qty', models.IntegerField()),
                ('PriceQty', models.IntegerField()),
                ('ProductFor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.product')),
            ],
        ),
    ]
